
package com.mcb.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Mon Apr 15 19:21:59 IST 2019
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getCCAcctTranList", namespace = "http://service.mcb.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCCAcctTranList", namespace = "http://service.mcb.com/", propOrder = {"shadowAccntNum", "statementCycle", "tranStatus", "sortOrder"})

public class GetCCAcctTranList {

    @XmlElement(name = "shadowAccntNum")
    private java.lang.String shadowAccntNum;
    @XmlElement(name = "statementCycle")
    private java.lang.String statementCycle;
    @XmlElement(name = "tranStatus")
    private java.lang.String tranStatus;
    @XmlElement(name = "sortOrder")
    private java.lang.String sortOrder;
	/**
	 * @return the shadowAccntNum
	 */
	public java.lang.String getShadowAccntNum() {
		return shadowAccntNum;
	}
	/**
	 * @param shadowAccntNum the shadowAccntNum to set
	 */
	public void setShadowAccntNum(java.lang.String shadowAccntNum) {
		this.shadowAccntNum = shadowAccntNum;
	}
	/**
	 * @return the statementCycle
	 */
	public java.lang.String getStatementCycle() {
		return statementCycle;
	}
	/**
	 * @param statementCycle the statementCycle to set
	 */
	public void setStatementCycle(java.lang.String statementCycle) {
		this.statementCycle = statementCycle;
	}
	/**
	 * @return the tranStatus
	 */
	public java.lang.String getTranStatus() {
		return tranStatus;
	}
	/**
	 * @param tranStatus the tranStatus to set
	 */
	public void setTranStatus(java.lang.String tranStatus) {
		this.tranStatus = tranStatus;
	}
	/**
	 * @return the sortOrder
	 */
	public java.lang.String getSortOrder() {
		return sortOrder;
	}
	/**
	 * @param sortOrder the sortOrder to set
	 */
	public void setSortOrder(java.lang.String sortOrder) {
		this.sortOrder = sortOrder;
	}

  
}

