
package com.mcb.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Mon Apr 15 19:19:36 IST 2019
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getDebitCreditCardInfo", namespace = "http://service.mcb.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDebitCreditCardInfo", namespace = "http://service.mcb.com/", propOrder = {"ownerOrHolder", "cardNumber"})

public class GetDebitCreditCardInfo {

    @XmlElement(name = "ownerOrHolder")
    private com.mcb.beans.OwnerOrHolder ownerOrHolder;
    @XmlElement(name = "cardNumber")
    private java.lang.String cardNumber;
	/**
	 * @return the ownerOrHolder
	 */
	public com.mcb.beans.OwnerOrHolder getOwnerOrHolder() {
		return ownerOrHolder;
	}
	/**
	 * @param ownerOrHolder the ownerOrHolder to set
	 */
	public void setOwnerOrHolder(com.mcb.beans.OwnerOrHolder ownerOrHolder) {
		this.ownerOrHolder = ownerOrHolder;
	}
	/**
	 * @return the cardNumber
	 */
	public java.lang.String getCardNumber() {
		return cardNumber;
	}
	/**
	 * @param cardNumber the cardNumber to set
	 */
	public void setCardNumber(java.lang.String cardNumber) {
		this.cardNumber = cardNumber;
	}

}

