<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetDebitCreditCardInfoImplService"
	targetNamespace="http://service.mcb.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://service.mcb.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jms="http://cxf.apache.org/transports/jms">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://service.mcb.com/" schemaLocation="getdebitcreditcardinfo_schema1.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="getDebitCreditCardInfoResponse">
		<wsdl:part name="parameters" element="tns:getDebitCreditCardInfoResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="getDebitCreditCardInfo">
		<wsdl:part name="parameters" element="tns:getDebitCreditCardInfo">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="GetDebitCreditCardInfo">
		<wsdl:operation name="getDebitCreditCardInfo">
			<wsdl:input name="getDebitCreditCardInfo" message="tns:getDebitCreditCardInfo">
			</wsdl:input>
			<wsdl:output name="getDebitCreditCardInfoResponse"
				message="tns:getDebitCreditCardInfoResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetDebitCreditCardInfoImplServiceSoapBinding"
		type="tns:GetDebitCreditCardInfo">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getDebitCreditCardInfo">
			<soap:operation soapAction="urn:GetDebitCreditCardInfo"
				style="document" />
			<wsdl:input name="getDebitCreditCardInfo">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="getDebitCreditCardInfoResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetDebitCreditCardInfoImplService">
		<wsdl:port name="GetDebitCreditCardInfoImplPort"
			binding="tns:GetDebitCreditCardInfoImplServiceSoapBinding">
			<soap:address
				location="http://localhost:8080/MCBDebitCreditTransactions/services/GetDebitCreditCardInfoImplPort" />
		</wsdl:port>
	</wsdl:service>

	<wsdl:binding name="GetDebitCreditCardInfoImplServiceJMSBinding"
		type="tns:GetDebitCreditCardInfo">
		<soap:binding style="document"
			transport="http://cxf.apache.org/transports/jms" />
		<wsdl:operation name="getDebitCreditCardInfo">
			<soap:operation soapAction="urn:GetDebitCreditCardInfo"
				style="document" />
			<wsdl:input name="getDebitCreditCardInfo">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="getDebitCreditCardInfoResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="GetDebitCreditCardInfoImplServiceJMSBinding">
		<wsdl:port name="GetDebitCreditCardInfoJMSImplPort"
			binding="tns:GetDebitCreditCardInfoImplServiceJMSBinding">
			<jms:address destinationStyle="queue"
				jndiConnectionFactoryName="wsQCF" jndiDestinationName="requestQueue">
				<jms:JMSNamingProperty name="java.naming.factory.initial"
					value="com.sun.jndi.fscontext.context.RefFSContextFactory" />
				<jms:JMSNamingProperty name="java.naming.provider.url"
					value="file:/C:/Ramu/JBoss-Proj/code/jboss-eap-7.1.0/jboss-eap-7.1/standalone/configuration/JNDIDirectory/" />
			</jms:address>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
